# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



#varibales
  variables:
    AZURE_VARIABLE: "AREEN"
    GIT_BRANCH: $(Build.sourceBranchName)
    GIT_REPO: $(Build.Repository.Name)

steps:

#SAY HELLO TO EVERYONE..!
- script: echo Hello,ICT DevOps!
  displayName: 'say hello!..'



#start the build  process
- script: bash build.sh $AZURE_VARIABLE 
  displayName: 'Run build.sh script'

#start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SAREEN@52.170.5.141'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true


